[package]
name = "louarchrs"
version = "0.1.0"
edition = "2024"

[profile.release]
opt-level = "z"
strip = true
lto = true
codegen-units = 1
panic = "abort"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
anyhow = "1"
dirs = "5"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
shellexpand = "3.1.1"
clap_complete = "4.5.66"
rusqlite = "0.38.0"
